export * from './update-doctor.dto'
export * from './create-doctor.dto'
export * from './create-consultation.dto'
export * from './update-consultation.dto'
export * from './create-rate.dto'
export * from './update-rate.dto'
export * from './create-specialization.dto'
export * from './update-specialization.dto'