export * from './add-specialization-to-doctor.dto'
export * from './update-specialization-to-doctor.dto'
export * from './update-specialization.dto'
export * from './create-specialization.dto'
export * from './specialization-to-doctor.dto'